version: "3.9"
services:
  ulp:
    build: .
    ports:
      - "3030:3030"
    volumes:
      - /home/hts/Git/ulp/.test_data:/data/:ro
  # Elastic + Kibana
#   elasticsearch:
#     build:
#       context: docker-elk/elasticsearch/
#       args:
#         ELK_VERSION: 7.16.0
#     volumes:
#       - ./docker-elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z 
#       - ./docker-elk/elasticsearch:/usr/share/elasticsearch/data:z
#     ports:
#       - "9200:9200"
#       - "9300:9300"
#     environment:
#       ES_JAVA_OPTS: "-Xmx256m -Xms256m"
#       ELASTIC_PASSWORD: changeme
#       # Use single node discovery in order to disable production mode and avoid bootstrap checks.
#       # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html 
#       discovery.type: single-node
#     networks:
#       - elk
#   kibana:
#     build:
#       context: docker-elk/kibana/
#       args:
#         ELK_VERSION: 7.16.0
#     volumes:
#       - ./docker-elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,z
#     ports:
#       - "5601:5601"
#     networks:
#       - elk
#     depends_on:
#       - elasticsearch
#   # 
# networks:
#   elk:
#     driver: bridge